/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetPreviewRouteImport } from './routes/widget-preview'
import { Route as ApiPublicReviewsWidgetDotjsRouteImport } from './routes/api/public/reviews-widget[.]js'
import { Route as ApiPublicReviewsDotjsonRouteImport } from './routes/api/public/reviews[.]json'
import { Route as ApiPublicHooksScrapeReviewsRouteImport } from './routes/api/public/hooks/scrape-reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetPreviewRoute = WidgetPreviewRouteImport.update({
  id: '/widget-preview',
  path: '/widget-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewsWidgetDotjsRoute =
  ApiPublicReviewsWidgetDotjsRouteImport.update({
    id: '/api/public/reviews-widget.js',
    path: '/api/public/reviews-widget.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReviewsDotjsonRoute = ApiPublicReviewsDotjsonRouteImport.update({
  id: '/api/public/reviews.json',
  path: '/api/public/reviews.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeReviewsRoute =
  ApiPublicHooksScrapeReviewsRouteImport.update({
    id: '/api/public/hooks/scrape-reviews',
    path: '/api/public/hooks/scrape-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/api/public/reviews-widget.js': typeof ApiPublicReviewsWidgetDotjsRoute
  '/api/public/reviews.json': typeof ApiPublicReviewsDotjsonRoute
  '/api/public/hooks/scrape-reviews': typeof ApiPublicHooksScrapeReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/api/public/reviews-widget.js': typeof ApiPublicReviewsWidgetDotjsRoute
  '/api/public/reviews.json': typeof ApiPublicReviewsDotjsonRoute
  '/api/public/hooks/scrape-reviews': typeof ApiPublicHooksScrapeReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/api/public/reviews-widget.js': typeof ApiPublicReviewsWidgetDotjsRoute
  '/api/public/reviews.json': typeof ApiPublicReviewsDotjsonRoute
  '/api/public/hooks/scrape-reviews': typeof ApiPublicHooksScrapeReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/widget-preview'
    | '/api/public/reviews-widget.js'
    | '/api/public/reviews.json'
    | '/api/public/hooks/scrape-reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/widget-preview'
    | '/api/public/reviews-widget.js'
    | '/api/public/reviews.json'
    | '/api/public/hooks/scrape-reviews'
  id:
    | '__root__'
    | '/'
    | '/widget-preview'
    | '/api/public/reviews-widget.js'
    | '/api/public/reviews.json'
    | '/api/public/hooks/scrape-reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WidgetPreviewRoute: typeof WidgetPreviewRoute
  ApiPublicReviewsWidgetDotjsRoute: typeof ApiPublicReviewsWidgetDotjsRoute
  ApiPublicReviewsDotjsonRoute: typeof ApiPublicReviewsDotjsonRoute
  ApiPublicHooksScrapeReviewsRoute: typeof ApiPublicHooksScrapeReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-preview': {
      id: '/widget-preview'
      path: '/widget-preview'
      fullPath: '/widget-preview'
      preLoaderRoute: typeof WidgetPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reviews-widget.js': {
      id: '/api/public/reviews-widget.js'
      path: '/api/public/reviews-widget.js'
      fullPath: '/api/public/reviews-widget.js'
      preLoaderRoute: typeof ApiPublicReviewsWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reviews.json': {
      id: '/api/public/reviews.json'
      path: '/api/public/reviews.json'
      fullPath: '/api/public/reviews.json'
      preLoaderRoute: typeof ApiPublicReviewsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-reviews': {
      id: '/api/public/hooks/scrape-reviews'
      path: '/api/public/hooks/scrape-reviews'
      fullPath: '/api/public/hooks/scrape-reviews'
      preLoaderRoute: typeof ApiPublicHooksScrapeReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WidgetPreviewRoute: WidgetPreviewRoute,
  ApiPublicReviewsWidgetDotjsRoute: ApiPublicReviewsWidgetDotjsRoute,
  ApiPublicReviewsDotjsonRoute: ApiPublicReviewsDotjsonRoute,
  ApiPublicHooksScrapeReviewsRoute: ApiPublicHooksScrapeReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
